"""First-principles Dirac traces. SymPy only simplifies our contractions.

No matrix-element or cross-section package is called. Signature is +---.
Both vector currents obey Ward identities on shell; the longitudinal
polarization term drops out. Park's unpolarized inverse process averages
over three incoming vector polarizations, giving 2/3 of the forward average.
"""
import itertools
from pathlib import Path
import sympy as sp

m, s, u, M2 = sp.symbols('m s u M2', real=True)
vectors = {'p':(1,0,0), 'f':(1,1,-1), 'r':(1,1,0), 'h':(1,0,-1)}
gram = sp.Matrix([[m*m,(s-m*m)/2,(m*m+M2-u)/2],
                  [(s-m*m)/2,0,(s+u-2*m*m)/2],
                  [(m*m+M2-u)/2,(s+u-2*m*m)/2,M2]])

def dot(a,b):
    """Scalar products of p, k, q expressed through s and u."""
    return (sp.Matrix(vectors[a]).T*gram*sp.Matrix(vectors[b]))[0]

def pairings(positions):
    """Wick pairings implementing the gamma anticommutator trace."""
    if not positions:
        yield 1, []
    else:
        for j in range(1,len(positions)):
            for sign,pairs in pairings(positions[1:j]+positions[j+1:]):
                yield (-1)**(j-1)*sign, [(positions[0],positions[j])]+pairs

def contracted_trace(word):
    """Contract repeated Lorentz indices mu,nu in each gamma trace."""
    total=0
    for sign,pairs in pairings(list(range(len(word)))):
        edges=[[] for _ in word]
        for a,b in pairs:
            edges[a].append(b); edges[b].append(a)
        for label in ('mu','nu'):
            loc=[i for i,x in enumerate(word) if x==label]
            a,b=loc
            edges[a].append(b); edges[b].append(a)
        seen=set(); term=4*sign
        for i in range(len(word)):
            if i in seen: continue
            stack=[i]; ends=[]
            while stack:
                j=stack.pop()
                if j in seen: continue
                seen.add(j)
                if word[j] in vectors: ends.append(word[j])
                stack.extend(edges[j])
            assert len(ends) in (0,2)
            term *= 4 if not ends else dot(*ends)
        total+=term
    return sp.expand(total)

def numerator(channel_a,channel_b):
    """Expand slash-plus-m numerators before taking a trace."""
    left={'s':['mu','r','nu'], 'u':['nu','h','mu']}[channel_a]
    right={'s':['nu','r','mu'], 'u':['mu','h','nu']}[channel_b]
    template=['f']+left+['p']+right
    slots=[i for i,x in enumerate(template) if x in vectors]
    total=0
    for keep in itertools.product((False,True),repeat=4):
        remove={i for i,k in zip(slots,keep) if not k}
        word=[x for i,x in enumerate(template) if i not in remove]
        if len(word)%2==0:
            total+=m**len(remove)*contracted_trace(word)
    return sp.factor(total)

def derive():
    """Return spin-averaged |M|^2 / (epsilon^2 e^4)."""
    ns=numerator('s','s'); nu=numerator('u','u')
    ni=numerator('s','u'); nj=numerator('u','s')
    assert sp.simplify(ni-nj)==0
    result=sp.factor((ns/(s-m*m)**2+nu/(u-m*m)**2+
                     (ni+nj)/((s-m*m)*(u-m*m)))/4)
    E,w=sp.symbols('E w',positive=True)
    massless=sp.factor(result.subs({M2:0,s:m*m+2*m*E,u:m*m-2*m*w}))
    cost=1-m*(1/w-1/E)
    klein_nishina=2*(E/w+w/E-(1-cost**2))
    assert sp.simplify(massless-klein_nishina)==0
    # Exact crossing symmetry makes the unpolarized inverse average 2/3.
    assert sp.simplify(result-result.xreplace({s:u,u:s}))==0
    # The external electron mass shell fixes t and both lab Jacobians.
    assert sp.simplify(dot('f','f')-m*m)==0
    check_explicit_matrices(result)
    a,b=sp.symbols('a b')
    compact=-2*(a/b+b/a+2*M2**2/(a*b)-2*M2*m**2*(1/a**2+1/b**2)
                -(2*M2+4*m**2)*(1/a+1/b)-4*m**4*(1/a+1/b)**2)
    assert sp.simplify(result-compact.subs({a:s-m*m,b:u-m*m}))==0
    print('PASS: interference traces agree; photon limit equals Klein-Nishina exactly')
    print('PASS: s/u symmetry and external electron mass shell')
    print('F(s,u)=',result)
    base=Path(__file__).resolve().parent
    (base/'output/trace.txt').write_text(str(result)+'\n'+sp.latex(result)+'\n')
    # Mechanical symbolic code generation, not a hand-copied literature formula.
    (base/'matrix_element_generated.h').write_text(
        '// Generated by derive.py from Dirac traces. Regenerate; do not edit.\n'
        '#pragma once\n#include <cmath>\n'
        'inline double TraceFactor(double s, double u, double m, double M2) {\n'
        '  const double a=s-m*m, b=u-m*m;\n'
        '  return '+sp.ccode(compact)+';\n}\n')
    return result

def check_explicit_matrices(result):
    """Independent exact Dirac-matrix check at a massive noncollinear point."""
    from sympy.physics.matrices import mgamma
    g=[mgamma(i) for i in range(4)]; I=sp.eye(4)
    p=[1,0,0,0]; k=[sp.Rational(3,2),0,0,sp.Rational(3,2)]
    q=[sp.Rational(5,4),sp.sqrt(5)/4,0,1]
    f=[p[i]+k[i]-q[i] for i in range(4)]
    def slash(v):
        return g[0]*v[0]-sum((g[i]*v[i] for i in range(1,4)),sp.zeros(4))
    S=4; U=-sp.Rational(5,4)
    rs=slash([p[i]+k[i] for i in range(4)])+I
    ru=slash([p[i]-q[i] for i in range(4)])+I
    ops=[[g[a]*rs*g[b]/(S-1)+g[b]*ru*g[a]/(U-1) for b in range(4)] for a in range(4)]
    P=slash(p)+I; F=slash(f)+I; sign=[1,-1,-1,-1]
    for a in range(4):
        wk=F*sum((ops[a][b]*sign[b]*k[b] for b in range(4)),sp.zeros(4))*P
        wq=F*sum((ops[b][a]*sign[b]*q[b] for b in range(4)),sp.zeros(4))*P
        assert wk.applyfunc(sp.simplify)==sp.zeros(4)
        assert wq.applyfunc(sp.simplify)==sp.zeros(4)
    tr=0
    for a in range(4):
        for b in range(4):
            op=ops[a][b]; bar=g[0]*op.conjugate().T*g[0]
            tr+=sign[a]*sign[b]*sp.trace(F*op*P*bar)/4
    assert sp.simplify(tr-result.subs({m:1,s:S,u:U,M2:sp.Rational(1,4)}))==0
    print('PASS: exact explicit Dirac matrices agree; both Ward identities vanish on shell')

if __name__=='__main__': derive()
