// Generated by derive.py from Dirac traces. Regenerate; do not edit.
#pragma once
#include <cmath>
inline double TraceFactor(double s, double u, double m, double M2) {
  const double a=s-m*m, b=u-m*m;
  return -4*pow(M2, 2)/(a*b) + 4*M2*pow(m, 2)*(pow(b, -2) + pow(a, -2)) - 2*a/b + 8*pow(m, 4)*pow(1.0/b + 1.0/a, 2) + 2*(2*M2 + 4*pow(m, 2))*(1.0/b + 1.0/a) - 2*b/a;
}
