// ROOT/C++ audit and recalculation. Run from code/darkphoton_v3.
#include "configuration.hxx"
#include <regex>
#include <chrono>

namespace Redo {
using namespace V3;
using Production::Require;
using Production::Close;
constexpr double efficiency=1./6, epsMax=.01;
// Danilov Eq. (5) has coefficient 2. It is a leading-order mixing expression.
double Split(double M,double mg,double eps){return std::pow(M*M-mg*mg,2)+2*eps*eps*M*M*(M*M+mg*mg);}
double Prod(double E,double M,double eps,const Config& c){return eps*eps*std::pow(M,4)/(Split(M,c.reactorM,eps)+std::pow(E*1e6*GammaWidthEV(c.absLength),2));}
double Det(double M,double eps,const Config& c){return eps*eps*std::pow(M,4)/Split(M,c.detectorM,eps);}
// Exclude +/-10% around either resonance; the detector Eq. (9) cannot be used there.
bool Resonance(double M,const Config& c){return std::abs(M/c.reactorM-1)<.1||std::abs(M/c.detectorM-1)<.1;}
double Geometry(const Config& c){return ElectronCount(c)*c.days*86400/(4*V3::pi*std::pow(c.baseline_m*100,2));}
// Contained visible energy Evis=EX, free electrons, constant selection efficiency.
double Events(double M,double eps,const Config& c,const Quadrature& q,double eta){return Geometry(c)*eta*q.Integrate([&](double E){return V3::PhotonSpectrum(E,c)*Prod(E,M,eps,c)*Det(M,eps,c)*KleinNishina(E);},c.roiLo,c.roiHi);}
double Limit(double M,const Config& c,const Quadrature& q,double eta){if(Resonance(M,c)||Events(M,epsMax,c,q,eta)<c.N95)return NAN;double lo=1e-14,hi=epsMax;for(int i=0;i<100;++i){double e=std::sqrt(lo*hi);if(Events(M,e,c,q,eta)>c.N95)hi=e;else lo=e;}return std::sqrt(lo*hi);}
// Time-reversed production amplitude; 2/3 is the massive unpolarized initial-state average.
// The medium model instead produces transverse states, for which this factor is absent.
double DetectionTotal(double E,double M,const Quadrature& q){if(E<=M)return 0;double s=electron*electron+M*M+2*electron*E,p=std::sqrt(E*E-M*M);
 double lo=(s-electron*electron)*(E+electron-p)/(2*s),hi=(s-electron*electron)*(E+electron+p)/(2*s);
 return q.Integrate([&](double w){double a=M*M+2*electron*E,b=-2*electron*w,F=Symbolic().numerator.Value(a,b,electron*electron,M*M)/(a*a*b*b);return (2./3)*e4*hbarc*hbarc*F/(32*Production::pi*electron*p*p);},lo,hi);}
// Park Eq. (1), massive inverse scattering, unit efficiency and original 1.96 sigma cap.
double ParkLimit(double M,const Config& c,const Quadrature& q){Source s;s.powerMW=c.powerMW;s.gammaMin=1;s.gammaMax=c.gammaHi;double K=Geometry(c)*q.Integrate([&](double E){return Spectrum(E,M,s,q)*DetectionTotal(E,M,q);},c.roiLo,c.roiHi);return std::pow(1.96*c.error/K,.25);}
// Require finite in-frame points, not merely nonempty PDF files.
void CheckGraph(const TGraph& g,double xmin,double xmax,double ymin,double ymax,const std::string& name){int n=0;for(int i=0;i<g.GetN();++i){double x,y;g.GetPoint(i,x,y);Require(std::isfinite(x)&&std::isfinite(y),"nonfinite plot point");if(x>=xmin&&x<=xmax&&y>=ymin&&y<=ymax)++n;}Require(n>=2,"empty/clipped curve: "+name);std::cout<<"VISIBLE "<<name<<": "<<n<<" points\n";}
void Save(TCanvas& cv,const std::string& stem,int expected){cv.Modified();cv.Update();int n=0;TIter next(cv.GetListOfPrimitives());while(auto o=next())if(o->InheritsFrom(TGraph::Class()))++n;Require(n>=expected,"canvas lost graphs: "+stem);for(auto ext:{".pdf",".svg",".png"})cv.SaveAs(("output/"+stem+ext).c_str());}
// Match Figure 1 masses, axes, power, source input, and overplot extracted Park PDF points.
void Figure1(const Quadrature& q){Source s;std::array<TGraph,3> theory,paper;std::array<double,3> masses={.1,.5,1};std::ifstream in("../park_production_v2/output/paper_bins.csv");Require(bool(in),"missing PDF bins");std::string line;std::getline(in,line);
 while(std::getline(in,line)){std::replace(line.begin(),line.end(),',',' ');std::istringstream row(line);double lo,hi,m,v;row>>lo>>hi>>m>>v;for(int j=0;j<3;++j)if(std::abs(m-masses[j])<1e-8)paper[j].SetPoint(paper[j].GetN(),(lo+hi)/2,v/1e21);}
 std::ofstream csv("output/figure1_recalculation.csv");csv<<"E_MeV,mass_MeV,rate_per_s_MeV\n"<<std::setprecision(16);
 TCanvas cv("park1","Park Figure 1 recalculated",1000,650);cv.SetLogy();cv.SetLeftMargin(.14);cv.SetBottomMargin(.14);cv.DrawFrame(0,.0015,4.3,3)->SetTitle(";E_{A'} [MeV];dN_{A'}/dE_{A'} / #epsilon^{2} [10^{21} s^{-1} MeV^{-1}]");TLegend leg(.52,.61,.89,.89);leg.SetTextSize(.026);leg.SetBorderSize(0);
 for(int j=0;j<3;++j){int col=j==0?kBlue+1:j==1?kBlack:kRed+1;for(int i=1;i<=430;++i){double E=.01*i,v=Spectrum(E,masses[j],s,q);csv<<E<<','<<masses[j]<<','<<v<<'\n';if(v>0)theory[j].SetPoint(theory[j].GetN(),E,v/1e21);}theory[j].SetLineColor(col);theory[j].SetLineWidth(2);paper[j].SetMarkerColor(col);paper[j].SetMarkerStyle(24);paper[j].SetMarkerSize(.3);CheckGraph(theory[j],0,4.3,.0015,3,"Figure1 calculation");CheckGraph(paper[j],0,4.3,.0015,3,"Figure1 Park points");theory[j].Draw("L SAME");paper[j].Draw("P SAME");leg.AddEntry(&theory[j],Form("Calculated M=%.1f MeV",masses[j]),"l");leg.AddEntry(&paper[j],Form("Park PDF M=%.1f MeV",masses[j]),"p");}leg.Draw();Save(cv,"figure1_comparison",6);}
// Keep all graph objects alive through canvas export; normalize at epsilon=1e-6, not 1.
void Produce(const Config& c){std::array<TGraph,3> curves;std::array<double,3> masses={1,10,1000};std::ofstream f("output/production_spectrum.csv");f<<"E_MeV,mass_eV,rate_div_epsilon2\n"<<std::setprecision(16);TCanvas cv("medium","Medium production",1000,650);cv.SetLogy();cv.SetLeftMargin(.14);cv.SetBottomMargin(.14);cv.DrawFrame(.2,1e10,10,1e22)->SetTitle(";E_{X}=E_{#gamma} [MeV];dN_{X}/dE / #epsilon^{2} [s^{-1} MeV^{-1}]");TLegend leg(.57,.7,.89,.89);leg.SetBorderSize(0);
 for(int j=0;j<3;++j){for(int i=0;i<=196;++i){double E=.2+.05*i,v=V3::PhotonSpectrum(E,c)*Prod(E,masses[j],1e-6,c)/1e-12;f<<E<<','<<masses[j]<<','<<v<<'\n';curves[j].SetPoint(i,E,v);}curves[j].SetLineColor(j==0?kBlue+1:j==1?kRed+1:kBlack);curves[j].SetLineWidth(3);CheckGraph(curves[j],.2,10,1e10,1e22,"Medium source");curves[j].Draw("L SAME");leg.AddEntry(&curves[j],Form("m_{X}=%.0f eV",masses[j]),"l");}leg.SetHeader("#epsilon=10^{-6}; configured reactor");leg.Draw();Save(cv,"figure1_medium",3);}
// Vector digitization of the actual Danilov line, independently calibrated from axis endpoints.
TGraph DanilovPoints(){std::ifstream in("output/danilov_page3.svg");Require(bool(in),"missing Danilov SVG");std::string line,path;int found=0;while(std::getline(in,line))if(line.find("stroke-width=\"25\"")!=std::string::npos&&line.find("stroke=\"rgb(0%, 0%, 0%)\"")!=std::string::npos&&line.find("stroke-dasharray")==std::string::npos){std::smatch m;std::regex r(" d=\"([^\"]+)\"");if(std::regex_search(line,m,r)){if(found)Require(path==m[1].str(),"different duplicate paths");path=m[1];++found;}}Require(found>=1,"ambiguous Danilov path");TGraph g;std::istringstream p(path);char cmd;double x,y;std::ofstream f("output/danilov_digitized.csv");f<<"mass_eV,epsilon\n"<<std::setprecision(16);
 while(p>>cmd>>x>>y){Require(cmd=='M'||cmd=='L',"unsupported SVG command");double M=std::pow(10.,-2+8*(x-660.011264)/(4739.022684-660.011264)),eps=std::pow(10.,-15+15*(y-.0192843)/(3149.523284-.0192843));g.SetPoint(g.GetN(),M,eps);f<<M<<','<<eps<<'\n';}Require(g.GetN()>20,"too few Danilov points");return g;}
// Medium curves stop at 10 keV, safely below the electron mass; leave resonance unclaimed.
void Limits(const Config& c,const Quadrature& q,double eta){TGraph low,high,ulow,uhigh,published,park,danilov=DanilovPoints();std::ofstream f("output/texono_limit.csv");f<<"mass_eV,epsilon95,events_at_limit,status\n"<<std::setprecision(16);
 for(int i=0;i<=320;++i){double M=std::pow(10.,-2+i*6./320),e=Limit(M,c,q,eta),u=Limit(M,c,q,1);f<<M<<','<<e<<','<<(std::isfinite(e)?Events(M,e,c,q,eta):NAN)<<','<<(Resonance(M,c)?"resonance_not_claimed":std::isfinite(e)?"bounded_root":"no_limit_below_epsilon_max")<<'\n';if(std::isfinite(e)){auto& g=M<c.reactorM?low:high;g.SetPoint(g.GetN(),M,e);}if(std::isfinite(u)){auto& g=M<c.reactorM?ulow:uhigh;g.SetPoint(g.GetN(),M,u);}}
 std::ofstream p("output/park_limit_recalculation.csv");p<<"mass_eV,epsilon_park_convention\n";for(int i=0;i<=60;++i){double M=std::pow(10.,-2+i*8./60),e=ParkLimit(M*1e-6,c,q);park.SetPoint(i,M,e);published.SetPoint(i,M,2.1e-5);p<<M<<','<<e<<'\n';}
 TCanvas cv("exclusion","TEXONO comparison",1100,700);cv.SetLogx();cv.SetLogy();cv.SetLeftMargin(.12);cv.SetBottomMargin(.14);cv.DrawFrame(.01,1e-6,1e6,.02)->SetTitle(";m_{X} [eV];#epsilon limit (see statistical conventions)");for(auto g:{&low,&high}){g->SetLineColor(kBlue+1);g->SetLineWidth(3);}for(auto g:{&ulow,&uhigh}){g->SetLineColor(kCyan+2);g->SetLineStyle(2);g->SetLineWidth(2);}published.SetLineColor(kRed+1);published.SetLineStyle(2);published.SetLineWidth(3);park.SetLineColor(kMagenta+1);park.SetLineStyle(7);park.SetLineWidth(2);danilov.SetLineColor(kBlack);danilov.SetLineWidth(2);
 for(auto g:{&low,&high,&ulow,&uhigh,&published,&park,&danilov}){CheckGraph(*g,.01,1e6,1e-6,.02,"TEXONO comparison");g->Draw("L SAME");}TLegend leg(.43,.61,.89,.89);leg.SetBorderSize(0);leg.SetTextSize(.026);leg.AddEntry(&published,"Park published: 2.1 #times 10^{-5}","l");leg.AddEntry(&danilov,"Danilov published (PDF extraction)","l");leg.AddEntry(&park,"Recomputed Park convention (1.96#sigma)","l");leg.AddEntry(&high,Form("This work: medium, efficiency %.3g",eta),"l");leg.AddEntry(&uhigh,"This work: medium, unit efficiency","l");leg.Draw();Save(cv,"figure2_texono_medium",7);
 std::cout<<std::setprecision(12)<<"medium_epsilon95_at_1keV="<<Limit(1000,c,q,eta)<<"; unit_efficiency="<<Limit(1000,c,q,1)<<"; Park_convention_at_1keV="<<ParkLimit(.001,c,q)<<'\n';}
// Test independent physics, numerical convergence, and N(epsilon95)=N95, not just finiteness.
void Checks(const Config& c,const Quadrature& q,double eta){Symbolic();CheckMatrices();Quadrature fine(c.nodes*2);for(double E:{.2,1.,4.,8.}){Close(Total(E,0,q),KleinNishina(E),1e-8,"production KN");Close(DetectionTotal(E,0,q),(2./3)*KleinNishina(E),1e-8,"inverse KN");for(double M:{.1,.5,1.})if(E>Threshold(M)){Close(Total(E,M,q),Reference15(E,M),1e-8,"Reference15");Close(Total(E,M,q),AnalyticTotal(E,M),1e-8,"analytic total");}}for(double M:{.1,.5,1.})for(double E:{2.,4.,8.}){double s=electron*electron+M*M+2*electron*E,Eg=(s-electron*electron)/(2*electron);double ratio=(2./3)*std::pow(s-electron*electron,2)/Kallen(s,electron*electron,M*M);Close(DetectionTotal(E,M,q),ratio*Total(Eg,M,q),1e-8,"massive detailed balance");}Close(Split(20,20,.001),.64,1e-12,"Danilov coefficient");Close(Det(10000,1e-6,c)/1e-12,1,1e-4,"medium vacuum");for(double M:{1.,10.,30.,1000.}){double e=Limit(M,c,q,eta);Require(std::isfinite(e),"missing root");Close(Events(M,e,c,q,eta),c.N95,1e-10,"root closure");Close(e,Limit(M,c,fine,eta),1e-8,"quadrature");}Require(std::isnan(Limit(20,c,q,eta))&&std::isnan(Limit(.001,c,q,eta)),"invalid domain claimed");std::cout<<"PASS: symbolic trace, independent matrices, Ward identities, Reference15, analytic totals, production/inverse KN, massive detailed balance\nPASS: Danilov coefficient, vacuum limit, bounded roots, event-cap closure, quadrature, invalid-domain rejection\n";}
}
int main(int argc,char** argv){try{auto start=std::chrono::steady_clock::now();gROOT->SetBatch(true);gStyle->SetOptStat(0);auto c=V3::ReadConfig(argc>1?argv[1]:"config.conf");double eta=argc>2?std::stod(argv[2]):c.eta;Production::Require(eta>0&&eta<=1,"invalid efficiency");V3::Quadrature q(c.nodes);Redo::Checks(V3::Config{},q,Redo::efficiency);Redo::Figure1(q);Redo::Produce(c);Redo::Limits(c,q,eta);std::ofstream f("output/runtime.txt");f<<"model=GPT-6\nreasoning_effort=not_exposed\ntokens_used=not_exposed\nROOT="<<gROOT->GetVersion()<<"\ncompiler="<<__VERSION__<<"\ncalculation_runtime_seconds="<<std::chrono::duration<double>(std::chrono::steady_clock::now()-start).count()<<'\n';std::cout<<"PASS: all exported curves finite, populated, in-frame and alive at save\n";}catch(const std::exception& e){std::cerr<<"FAIL: "<<e.what()<<'\n';return 1;}}
